#+ endpoint: https://fuseki.sharemusic.se/museit/sparql

PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>


SELECT ?localItem ?localItemLabel ?wikidataItem WHERE {
  ?localItem ?localProperty ?wikidataItem .
}

